# Generated by Django 3.0.4 on 2020-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_person_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docs',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
