# Generated by Django 3.0.4 on 2020-03-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20200316_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('alter_salary', 'Usuário pode alterar valor salario'),)},
        ),
    ]
