# Generated by Django 3.0.4 on 2020-03-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200319_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('alter_salary', 'Usuário pode alterar valor salario'), ('manager_dashboard_clients', 'Can view clients manager dashboar'))},
        ),
    ]
