# Generated by Django 3.0.4 on 2020-03-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200319_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('alter-salary', 'Usuário pode alterar valor salario'), ('manager-dashboard-clients', 'Can view clients manager dashboar'))},
        ),
    ]
