# Generated by Django 3.0.4 on 2020-03-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200319_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('alter_salary', 'Usuário pode alterar valor salario'), ('manager_dashboard-clients', 'Can view clients manager dashboar'))},
        ),
    ]
